In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root / "src"))

from midv_preprocessing import collect_midv_metadata, save_metadata

midv_root = project_root / "data" / "midv"
output_path = project_root / "data" / "processed" / "midv_metadata.csv"

print("MIDV path:", midv_root)


df_midv = collect_midv_metadata(midv_root)
print(df_midv.head())
print(df_midv.shape)
print(df_midv[["width", "height"]].head())

save_metadata(df_midv, output_path)

ImportError: cannot import name 'collect_midv_metadata' from 'midv_preprocessing' (c:\Users\Admin\Desktop\thesis\multimodal-fraud-detection-thesis\src\midv_preprocessing.py)

The MIDV metadata were collected successfully from the original dataset structure.  
In total, 4,000 original document images were identified and labeled as "bona_fide".

At this stage, MIDV is used as a source of authentic document images.  
These samples will later serve as bona fide examples in the image classification task,

In [2]:
df_midv.head(10)

,sample_id,source_dataset,source_type,doc_type,file_name,file_stem,image_path,annotation_path,final_label,is_synthetic,width,height
0,midv_000000,midv,photo,alb_id,00.jpg,00,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
1,midv_000001,midv,photo,alb_id,01.jpg,01,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
2,midv_000002,midv,photo,alb_id,02.jpg,02,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
3,midv_000003,midv,photo,alb_id,03.jpg,03,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
4,midv_000004,midv,photo,alb_id,04.jpg,04,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
5,midv_000005,midv,photo,alb_id,05.jpg,05,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
6,midv_000006,midv,photo,alb_id,06.jpg,06,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
7,midv_000007,midv,photo,alb_id,07.jpg,07,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
8,midv_000008,midv,photo,alb_id,08.jpg,08,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032
9,midv_000009,midv,photo,alb_id,09.jpg,09,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,c:\Users\Admin\Desktop\thesis\multimodal-fraud...,bona_fide,False,2268,4032

In [2]:
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root / "src"))

In [3]:
from pathlib import Path
from midv_preprocessing import build_midv_genuine_dataframe, save_metadata

midv_root = Path(r"C:\Users\Admin\Desktop\thesis\multimodal-fraud-detection-thesis\data\midv")

print("MIDV path:", midv_root)
print("Exists:", midv_root.exists())

df_midv = build_midv_genuine_dataframe(midv_root)

print(df_midv.head())
print(df_midv.shape)
print(df_midv["image_class"].value_counts(dropna=False))
print(df_midv["doc_type"].value_counts(dropna=False))
print(df_midv["source_type"].value_counts(dropna=False))

save_metadata(
    df_midv,
    r"C:\Users\Admin\Desktop\thesis\multimodal-fraud-detection-thesis\data\processed\midv_image_manifest.csv"
)

MIDV path: C:\Users\Admin\Desktop\thesis\multimodal-fraud-detection-thesis\data\midv
Exists: True
                                          image_path source_dataset  \
0  C:\Users\Admin\Desktop\thesis\multimodal-fraud...           midv
1  C:\Users\Admin\Desktop\thesis\multimodal-fraud...           midv
2  C:\Users\Admin\Desktop\thesis\multimodal-fraud...           midv
3  C:\Users\Admin\Desktop\thesis\multimodal-fraud...           midv
4  C:\Users\Admin\Desktop\thesis\multimodal-fraud...           midv

  image_class   group_key doc_type source_type file_name split_source  \
0   bona_fide  alb_id__00   alb_id       photo    00.jpg         None
1   bona_fide  alb_id__01   alb_id       photo    01.jpg         None
2   bona_fide  alb_id__02   alb_id       photo    02.jpg         None
3   bona_fide  alb_id__03   alb_id       photo    03.jpg         None
4   bona_fide  alb_id__04   alb_id       photo    04.jpg         None

   original_label               relative_path file_stem suffix
0               0  photo\images\alb_id\00.jpg        00   .jpg
1               0  photo\images\alb_id\01.jpg        01   .jpg
2               0  photo\images\alb_id\02.jpg        02   .jpg
3               0  photo\images\alb_id\03.jpg        03   .jpg
4               0  photo\images\alb_id\04.jpg        04   .jpg
(4000, 12)
image_class
bona_fide    4000
Name: count, dtype: int64
doc_type
alb_id                  400
aze_passport            400
esp_id                  400
est_id                  400
fin_id                  400
grc_passport            400
lva_passport            400
rus_internalpassport    400
srb_passport            400
svk_id                  400
Name: count, dtype: int64
source_type
photo           1000
scan_rotated    1000
scan_upright    1000
templates       1000
Name: count, dtype: int64
Saved metadata to: C:\Users\Admin\Desktop\thesis\multimodal-fraud-detection-thesis\data\processed\midv_image_manifest.csv

In [4]:
df_midv.head(10)

,image_path,source_dataset,image_class,group_key,doc_type,source_type,file_name,split_source,original_label,relative_path,file_stem,suffix
0,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__00,alb_id,photo,00.jpg,None,0,photo\images\alb_id\00.jpg,00,.jpg
1,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__01,alb_id,photo,01.jpg,None,0,photo\images\alb_id\01.jpg,01,.jpg
2,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__02,alb_id,photo,02.jpg,None,0,photo\images\alb_id\02.jpg,02,.jpg
3,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__03,alb_id,photo,03.jpg,None,0,photo\images\alb_id\03.jpg,03,.jpg
4,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__04,alb_id,photo,04.jpg,None,0,photo\images\alb_id\04.jpg,04,.jpg
5,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__05,alb_id,photo,05.jpg,None,0,photo\images\alb_id\05.jpg,05,.jpg
6,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__06,alb_id,photo,06.jpg,None,0,photo\images\alb_id\06.jpg,06,.jpg
7,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__07,alb_id,photo,07.jpg,None,0,photo\images\alb_id\07.jpg,07,.jpg
8,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__08,alb_id,photo,08.jpg,None,0,photo\images\alb_id\08.jpg,08,.jpg
9,C:\Users\Admin\Desktop\thesis\multimodal-fraud...,midv,bona_fide,alb_id__09,alb_id,photo,09.jpg,None,0,photo\images\alb_id\09.jpg,09,.jpg